# Site settings
title: Daniel Klepacki
description: Personal website of one machine learning enthusiast.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vonski.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Daniel Klepacki
user_description: TBA
user_title: Machine Learning Engineer
email: klepacki.daniel.pro@gmail.com
twitter_username: daniel_klepacki
github_username:  Vonski
facebook_url: dnaiel.klepacki
linkedin_url: klepacki-daniel


exclude: ['package.json', 'src' , 'node_modules']
